name: tp_package
description: tp package
version: 1.0.5
homepage: https://github.com/thienphan1996/flutter_tp_package

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  connectivity_plus: ^1.1.0

  flutter:
    sdk: flutter

  flutter_share: ^2.0.0

  fluttertoast: ^8.0.8

  google_mobile_ads: ^0.13.5

  intl: ^0.17.0

  responsive_framework: ^0.1.4

  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
